version: "3.3"
services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    ports:
      - 3002:27017
    volumes:
      - /data/db
  backend:
    container_name: backend
    build: ./backend
    command: npm run develop
    volumes:
      - ./backend/src:/app/src
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongo:27017
      - JWT_SECRET=potato
      - SALT_ROUNDS=10
    ports:
      - 3001:3001
    depends_on:
      - mongo
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    depends_on:
      - backend
